
data_bin: ec30/fairseq-data-bin-sharded/shard0:ec30/fairseq-data-bin-sharded/shard1:ec30/fairseq-data-bin-sharded/shard2:ec30/fairseq-data-bin-sharded/shard3:ec30/fairseq-data-bin-sharded/shard4
save_dir: checkpoints/ec30/k_95

restore-file: ec30/checkpoint_best_m2m.pt

reset_dataloader: true
reset_meters: true
reset_optimizer: true
reset_lr_scheduler: true

langs: en,de,nl,sv,da,af,lb,fr,es,it,pt,ro,oc,ru,cs,pl,bg,uk,sr,hi,bn,kn,mr,sd,gu,ar,he,ha,mt,ti,am
lang_pairs: en-de,en-nl,en-sv,en-da,en-af,en-lb,en-fr,en-es,en-it,en-pt,en-ro,en-oc,en-ru,en-cs,en-pl,en-bg,en-uk,en-sr,en-hi,en-bn,en-kn,en-mr,en-sd,en-gu,en-ar,en-he,en-ha,en-mt,en-ti,en-am,de-en,nl-en,sv-en,da-en,af-en,lb-en,fr-en,es-en,it-en,pt-en,ro-en,oc-en,ru-en,cs-en,pl-en,bg-en,uk-en,sr-en,hi-en,bn-en,kn-en,mr-en,sd-en,gu-en,ar-en,he-en,ha-en,mt-en,ti-en,am-en


# model
arch: transformer_vaswani_wmt_en_de_big_with_mask
share_decoder_input_output_embed: true
dropout: 0.1
attention_dropout: 0.1
encoder_normalize_before: true
decoder_normalize_before: true
share_decoder_input_output_embed: true
max_source_positions: 256
max_target_positions: 256

task: mask_translation_multi_simple_epoch
no-mask-output-project: true
no-save-static-mask: true
mask_path: "'{\"en-de\": \"scripts/masks/en-de.pt\",
              \"en-nl\": \"scripts/masks/en-nl.pt\",
              \"en-sv\": \"scripts/masks/en-sv.pt\",
              \"en-da\": \"scripts/masks/en-da.pt\",
              \"en-af\": \"scripts/masks/en-af.pt\",
              \"en-lb\": \"scripts/masks/en-lb.pt\",
              \"en-fr\": \"scripts/masks/en-fr.pt\",
              \"en-es\": \"scripts/masks/en-es.pt\",
              \"en-it\": \"scripts/masks/en-it.pt\",
              \"en-pt\": \"scripts/masks/en-pt.pt\",
              \"en-ro\": \"scripts/masks/en-ro.pt\",
              \"en-oc\": \"scripts/masks/en-oc.pt\",
              \"en-ru\": \"scripts/masks/en-ru.pt\",
              \"en-cs\": \"scripts/masks/en-cs.pt\",
              \"en-pl\": \"scripts/masks/en-pl.pt\",
              \"en-bg\": \"scripts/masks/en-bg.pt\",
              \"en-uk\": \"scripts/masks/en-uk.pt\",
              \"en-sr\": \"scripts/masks/en-sr.pt\",
              \"en-hi\": \"scripts/masks/en-hi.pt\",
              \"en-bn\": \"scripts/masks/en-bn.pt\",
              \"en-kn\": \"scripts/masks/en-kn.pt\",
              \"en-mr\": \"scripts/masks/en-mr.pt\",
              \"en-sd\": \"scripts/masks/en-sd.pt\",
              \"en-gu\": \"scripts/masks/en-gu.pt\",
              \"en-ar\": \"scripts/masks/en-ar.pt\",
              \"en-he\": \"scripts/masks/en-he.pt\",
              \"en-ha\": \"scripts/masks/en-ha.pt\",
              \"en-mt\": \"scripts/masks/en-mt.pt\",
              \"en-ti\": \"scripts/masks/en-ti.pt\",
              \"en-am\": \"scripts/masks/en-am.pt\",
              \"de-en\": \"scripts/masks/de-en.pt\",
              \"nl-en\": \"scripts/masks/nl-en.pt\",
              \"sv-en\": \"scripts/masks/sv-en.pt\",
              \"da-en\": \"scripts/masks/da-en.pt\",
              \"af-en\": \"scripts/masks/af-en.pt\",
              \"lb-en\": \"scripts/masks/lb-en.pt\",
              \"fr-en\": \"scripts/masks/fr-en.pt\",
              \"es-en\": \"scripts/masks/es-en.pt\",
              \"it-en\": \"scripts/masks/it-en.pt\",
              \"pt-en\": \"scripts/masks/pt-en.pt\",
              \"ro-en\": \"scripts/masks/ro-en.pt\",
              \"oc-en\": \"scripts/masks/oc-en.pt\",
              \"ru-en\": \"scripts/masks/ru-en.pt\",
              \"cs-en\": \"scripts/masks/cs-en.pt\",
              \"pl-en\": \"scripts/masks/pl-en.pt\",
              \"bg-en\": \"scripts/masks/bg-en.pt\",
              \"uk-en\": \"scripts/masks/uk-en.pt\",
              \"sr-en\": \"scripts/masks/sr-en.pt\",
              \"hi-en\": \"scripts/masks/hi-en.pt\",
              \"bn-en\": \"scripts/masks/bn-en.pt\",
              \"kn-en\": \"scripts/masks/kn-en.pt\",
              \"mr-en\": \"scripts/masks/mr-en.pt\",
              \"sd-en\": \"scripts/masks/sd-en.pt\",
              \"gu-en\": \"scripts/masks/gu-en.pt\",
              \"ar-en\": \"scripts/masks/ar-en.pt\",
              \"he-en\": \"scripts/masks/he-en.pt\",
              \"ha-en\": \"scripts/masks/ha-en.pt\",
              \"mt-en\": \"scripts/masks/mt-en.pt\",
              \"ti-en\": \"scripts/masks/ti-en.pt\",
              \"am-en\": \"scripts/masks/am-en.pt\"}'"
sampling_method: temperature
sampling_temperature: 5
encoder_langtok: src
decoder_langtok: true

criterion: label_smoothed_cross_entropy
label_smoothing: 0.1
optimizer: adam
adam_betas: "'(0.9, 0.98)'"
adam_eps: 1e-06
clip_norm: 0.0
lr: 5e-4
lr_scheduler: inverse_sqrt
warmup_updates: 4000
weight_decay: 0.0

# 4 gpu
max_tokens: 7680
update_freq: 21
distributed_world_size: 4
ddp_backend: no_c10d
ddp_comm_hook: fp16
max_update: 900000
fp16: true

patience: 20
save_interval: 500
save_interval_updates: 500
validate_interval: 500
validate_interval_updates: 500
keep_interval_updates: 3
seed: 222
log_format: simple
log_interval: 20

skip_invalid_size_inputs_valid_test: true
